#!/data/data/com.termux/files/usr/bin/bash

appTest(){
[[ -z $(command -v xxh32sum) ]] && { echo "xxh32sum? Paket XXHASH installieren."; exit; }
[[ -z $(command -v base91) ]] && { echo "base91? Programm BASE91 compilieren."; exit; }
[[ -z $(command -v file) ]] && { echo "file? Paket FILE installieren."; exit; }; }

info(){
echo "Telex  DateiName [z] [Baud] [Modem-SteuerParameter]           Version 1.5"
echo "TELEX: Dienstprogramm für MINIMODEM zum bequemen akustischen Dateiversand"
echo "       Der Dateiname muss der erste Parameter sein. Die anderen werden an"
echo "       MINIMODEM unverändert durchgereicht. Ohne Parameter  wird mit 1200"
echo "       Baud im  Format BELL-202 bei 48 kHz Samplingrate gesendet.  Binäre"
echo "       Dateien werden erkannt und als ein selbstdekodierendes Shellskript"
echo "       base32/64/92 codiert versandt. “z” zippt die Datei zuvor und lässt"
echo "       sie ebenfalls vom Skript dekomprimieren."; }

delay(){
echo; for ((tmr=$1; tmr>-1; tmr=tmr-1)); do
   echo -e "\033[1A\e[0;33mCarrier in $tmr Sekunden\033[0m"; sleep 1
done; }

txtTelex(){
echo "+++++ Minimodem Telegramm +++++++" >>$wvtxt
echo "+++++ Versandzeit: $(date)"        >>$wvtxt
echo "+++++ Sendeparameter: $cli"        >>$wvtxt
echo "+++++ Dateiname: $datei"           >>$wvtxt
echo                                     >>$wvtxt
cat $datei                               >>$wvtxt
echo                                     >>$wvtxt
echo "++++++ Telex Telegramm Ende +++++" >>$wvtxt; }

binTelex(){                                                                                    echo >$wvtxt; echo >>$wvtxt
echo "#!/usr/bin/bash"                   >>$wvtxt
echo "# +++++ Minimodem Telegramm +++++" >>$wvtxt
echo "# Versandzeit: $(date)"            >>$wvtxt
echo "# Automatic decoding shell script" >>$wvtxt
echo "cat << EOF | $baseX -d -i >$datei" >>$wvtxt
cat $datei | $baseX                      >>$wvtxt
echo "EOF"                               >>$wvtxt
echo "chksend=$chksum"                   >>$wvtxt
echo "chkrecv=\$($chckX $datei |awk '{print \$1}')"        >>$wvtxt
echo '[ $chkrecv != $chksend ] && echo Checksummenfehler!' >>$wvtxt
echo "z=$z; [ -z \$z ] || unxz $datei"                     >>$wvtxt
echo "# +++++++++++++ Telex Telegramm Ende ++++++++++++++" >>$wvtxt; }

[[ -e $1 ]] || { echo "Datei nicht gefunden"; info; exit; } && { datei=$1; shift; }
[[ $1 == "z" ]] && { shift; xz -9vc $datei >$datei.xz; datei=$datei.xz; z=1; }

#appTest
baseX=base64
chckX=sha1sum
wvdat=$TEMP/MiMo$$.wav
wvtxt=$TEMP/MiMo$$.txt
cli="$@"; [[ -z $cli ]] && cli=1200
chksum=$($chckX $datei |awk '{print $1}')

[[ -z $(file $datei |grep text) ]] && binTelex || txtTelex

cat $wvtxt |minimodem -f $wvdat -t $cli
[[ -z $z ]] || echo "  XZ-komprimiert zu $datei"
echo "Send File: $(ls -hs $wvtxt)"
echo "Send Wave: $(ls -hs $wvdat)"
ffprobe -hide_banner $wvdat; delay 3
termux-media-player play $wvdat

echo -e "\033[0;33mTonausgabe abbrechen: “ply stop” bzw. “termux-media-player stop”.\033[0m"
[[ -z $z ]] || rm $datei
